dbShopeeAutomationV2/dbShopeeAutomationV2/Controllers/ScanQRCodeController.cs
using dbShopeeAutomationV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dbShopeeAutomationV2.Controllers
{
    public class ScanQRCodeController : AdminController
    {
        dbShopeeAutomationV2Entities db = new dbShopeeAutomationV2Entities();

        // GET: ScanQRCode
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitCode(string invoice_title)
        {
            var model = db.TShopeeInvoices.FirstOrDefault(it => it.invoice_title.ToLower().Equals(invoice_title.ToLower()));

            // Check If Invoice Code Exist in Database
            if(model == null) {
                return Content("Error! Invalid Invoice Code!");
            }

            int c_inv_sta_id = dbStatusFunction.invoiceStatusID("Complete");

            if (c_inv_sta_id == -1) {
                return Content("Error! Invoice Status Code for 'Complete' does not exist!");
            }
            
            if(model.invoice_status_id != c_inv_sta_id)
            {
                string username = User.Identity.Name;

                model.invoice_status_id = c_inv_sta_id;
                model.invoice_completed_date = DateTime.Now;

                db.SaveChanges();

                return Content($"Success! Invoice Code {model.invoice_title} was successfully updated!");
            }

            return Content($"Error! You have already scanned Invoice Code {model.invoice_title}!");
        }
    }
}

dbShopeeAutomationV2/dbShopeeAutomationV2/Views/ScanQRCode/Index.cshtml
@{
    ViewBag.Title = "Scan QRCode";
    Layout = "~/Views/Shared/_QRCodeLayout.cshtml";
}

<style>
    .img {
        width: 200px;
        height: 200px;
    }

    .qr_div_width {
        width: 600px;
    }

    /* Mobile Phone */
    @@media (max-width: 767px) {
        .qr_div_width {
            width: 300px;
        }
    }
</style>

<div class="d-flex align-items-center justify-content-center">
    <div class="p-3">
        <div class="border border-dark">
            <div class="container">

                <div class="row">
                    <div class="bg-dark text-center text-white h1">@ViewBag.Title</div>
                </div>

                <div class="text-center">
                    <div id="reader"></div>
                </div>

                <div class="my-2"></div>

                @using (Html.BeginForm("SubmitCode", "ScanQRCode", FormMethod.Post, new { @Id = "QRCodeForm" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="row">
                        <div class="col">
                            @Html.TextBox("invoice_title", "", new { @Class = "form-control", @Type = "text", @Placeholder = "Insert Invoice Code" })
                        </div>
                        <div class="col">
                            <input type="submit" class="btn btn-success form-control" value="Submit QRCode" />
                        </div>
                    </div>
                }
                <div class="text-center h4" id="resp_msg"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        function onScanSuccess(decodedText, decodedResult) {
            $("input[name='invoice_title']").val(`${decodedText}`);
        }

        var html5QrcodeScanner = new Html5QrcodeScanner("reader", { fps: 10, qrbox: 250 });
        html5QrcodeScanner.render(onScanSuccess);

        let qrCodeForm = $("form[id='QRCodeForm']");
        const qrCodeForm_actionLink = qrCodeForm.attr("action");
        const qrCodeForm_methodType = qrCodeForm.attr("method");

        qrCodeForm.submit(e => {
            e.preventDefault();

            $.ajax({
                url: qrCodeForm_actionLink,
                type: qrCodeForm_methodType,
                data: qrCodeForm.serialize(),
                success: resp => {
                    $("#resp_msg").html(resp);
                    setTimeout(_ => {
                        $("#resp_msg").html("");
                    }, 2000);
                }
            });
        });
    });
</script>