dbShopeeAutomationV2/dbShopeeAutomationV2/Controllers/DailyTaskController.cs
using dbShopeeAutomationV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dbShopeeAutomationV2.Controllers
{
    public class DailyTaskController : AdminController
    {

        dbShopeeAutomationV2Entities db = new dbShopeeAutomationV2Entities();

        public int numOfOrdersLeft(IEnumerable<TShopeeInvoice> invoiceList)
        {
            int inv_sta_id = dbStatusFunction.invoiceStatusID("Incomplete");
            int p_inv_sta_id = dbStatusFunction.invoiceStatusID("Packaging");

            return invoiceList
                .Where(it => it.invoice_status_id == inv_sta_id || it.invoice_status_id == p_inv_sta_id)
                .ToList().Count;
        }

        // GET: DailyTask
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DailyTaskPartial()
        {
            // Return only Incomplete, Packaging and Orders with Completed Dates on Today
            var model = db.TShopeeInvoices.AsEnumerable().Where(it =>
            {
                if (it.invoice_completed_date == null)
                {
                    return true;
                }

                DateTime tmp = (DateTime)it.invoice_completed_date;
                return tmp.Date == DateTime.Now.Date;
            });

            ViewData["num_of_orders_left"] = numOfOrdersLeft(model);
            return PartialView("_DailyTaskPartial", model);
        }

        [HttpPost]
        public ActionResult Show(TShopeeInvoice item)
        {
            IEnumerable<TShopeeInvoice> model;

            DateTime inv_com_dt = (DateTime)item.invoice_completed_date;

            if (inv_com_dt.Date == DateTime.Now.Date)
            {
                // Return only Incomplete, Packaging and Orders with Completed Dates on Today
                model = db.TShopeeInvoices.AsEnumerable().Where(it =>
                {
                    if (it.invoice_completed_date == null)
                    {
                        return true;
                    }

                    DateTime tmp = (DateTime)it.invoice_completed_date;
                    return tmp.Date == DateTime.Now.Date;
                });

                ViewData["num_of_orders_left"] = numOfOrdersLeft(model);
                return PartialView("_DailyTaskPartial", model);
            }

            // Return only Specific Date that were completed on that day
            model = db.TShopeeInvoices.AsEnumerable().Where(it =>
            {
                if (it.invoice_completed_date == null)
                {
                    return false;
                }

                DateTime tmp = (DateTime)it.invoice_completed_date;
                return tmp.Date == inv_com_dt.Date.Date;
            });

            ViewData["num_of_orders_left"] = numOfOrdersLeft(model);

            return PartialView("_DailyTaskPartial", model);
        }

        [HttpPost]
        public ActionResult GenerateSummary()
        {
            string[] invoice_id_str_arr = Request.Form.GetValues("invoice_id");

            if (invoice_id_str_arr != null)
            {
                int[] invoice_id_arr = invoice_id_str_arr.Select(x => int.Parse(x)).ToArray();

                // Create Empty Product Summary List
                Dictionary<int, ProductSummary> productSummaryDict = new Dictionary<int, ProductSummary>();

                // Packaging Invoice Status ID
                int p_inv_sta_id = dbStatusFunction.invoiceStatusID("Packaging");

                string username = User.Identity.Name;

                foreach (var invoice_id in invoice_id_arr)
                {
                    // 0. Update Invoice Status to Packaging
                    var invoice = db.TShopeeInvoices.FirstOrDefault(it => it.invoice_id == invoice_id);

                    // 1. Get Order ID
                    int order_id = (int) invoice.order_id;

                    // 2. Get List of Order Item
                    List<TShopeeOrderItem> orderItemList = db.TShopeeOrderItems.Where(it => it.order_id == order_id).ToList();

                    // 3. Loop Through List of Order Item
                    foreach (var order_item in orderItemList)
                    {
                        int order_item_id = order_item.order_item_id;

                        // 4. Get Product
                        var product = db.TShopeeProducts.FirstOrDefault(it => it.product_id == order_item.product_id);

                        int product_id = product.product_id;
                        int quantity = (int)order_item.quantity;

                        // 5. Check if Product exist in product Summary Dict
                        if (productSummaryDict.ContainsKey(product_id))
                        {
                            productSummaryDict[product_id].addQuantity(quantity);
                        }
                        else
                        {
                            // 6. Create New Product Summary Class
                            string product_name = product.name;

                            // Product Brand
                            var product_brand = db.TShopeeProductBrands.FirstOrDefault(it => it.product_brand_id == product.product_brand_id);
                            string product_brand_str = product_brand.code;

                            // Product Model
                            var product_model = db.TShopeeProductModels.FirstOrDefault(it => it.product_model_id == product.product_model_id);
                            string product_model_str = product_model.code;

                            // Product Type
                            var product_type = db.TShopeeProductTypes.FirstOrDefault(it => it.product_type_id == product.product_type_id);
                            string product_type_str = product_type.code;

                            // Product Category
                            var product_category = db.TShopeeProductCategories.FirstOrDefault(it => it.product_category_id == product.product_category_id);
                            string product_category_str = product_category.code;

                            var productSummary = new ProductSummary(
                                product_id, product_name,
                                product_brand_str, product_category_str, 
                                product_model_str, product_type_str, 
                                quantity);

                            productSummaryDict.Add(product_id, productSummary);
                        }
                    }

                    invoice.invoice_status_id = p_inv_sta_id;
                    db.SaveChanges();
                }

                // 7. Create List of productSummary
                IList<ProductSummary> model = new List<ProductSummary>();

                // 8. Loop Throught Dictionary to Populate List of ProductSummary
                foreach (var kvp in productSummaryDict)
                {
                    model.Add(kvp.Value);
                }

                return PartialView("_SummaryListingPartial", model);
            }

            return Content("");
        }

        [HttpPost]
        public ActionResult PrintBill(int invoice_id)
        {
            // Stock Warehouse
            var stockWarehouse = db.TShopeeStockWarehouses.ToList().ElementAt(0);

            // Invoice
            var invoice = db.TShopeeInvoices.FirstOrDefault(it => it.invoice_id == invoice_id);

            // Customer
            var customer = db.TShopeeCustomers.FirstOrDefault(it => it.customer_id == invoice.customer_id);

            // Order
            var order = db.TShopeeOrders.FirstOrDefault(it => it.order_id == invoice.order_id);

            // Create Empty Product Summary List
            Dictionary<int, ProductSummary> productSummaryDict = new Dictionary<int, ProductSummary>();

            // 1. Get Order ID
            int order_id = (int)invoice.order_id;

            // 2. Get List of Order Item
            List<TShopeeOrderItem> orderItemList = db.TShopeeOrderItems.Where(it => it.order_id == order_id).ToList();

            // 3. Loop Through List of Order Item
            foreach (var order_item in orderItemList)
            {
                int order_item_id = order_item.order_item_id;

                // 4. Get Product
                var product = db.TShopeeProducts.FirstOrDefault(it => it.product_id == order_item.product_id);

                int product_id = product.product_id;
                int quantity = (int)order_item.quantity;

                // 5. Check if Product exist in product Summary Dict
                if (productSummaryDict.ContainsKey(product_id))
                {
                    productSummaryDict[product_id].addQuantity(quantity);
                }
                else
                {
                    // 6. Create New Product Summary Class
                    string product_name = product.name;

                    // Product Brand
                    var product_brand = db.TShopeeProductBrands.FirstOrDefault(it => it.product_brand_id == product.product_brand_id);
                    string product_brand_str = product_brand.code;

                    // Product Model
                    var product_model = db.TShopeeProductModels.FirstOrDefault(it => it.product_model_id == product.product_model_id);
                    string product_model_str = product_model.code;

                    // Product Type
                    var product_type = db.TShopeeProductTypes.FirstOrDefault(it => it.product_type_id == product.product_type_id);
                    string product_type_str = product_type.code;

                    // Product Category
                    var product_category = db.TShopeeProductCategories.FirstOrDefault(it => it.product_category_id == product.product_category_id);
                    string product_category_str = product_category.code;

dbShopeeAutomationV2/dbShopeeAutomationV2/Views/DailyTask/Index.cshtml
@model dbShopeeAutomationV2.Models.TShopeeInvoice

@{
    ViewBag.Title = "Daily Task";
    Layout = "~/Views/Shared/_TaskLayout.cshtml";
}

<style>
    /* Mobile Phone */
    @@media (max-width: 767px) {
        th:nth-child(3),
        th:nth-child(4),
        th:nth-child(5),
        td:nth-child(3),
        td:nth-child(4),
        td:nth-child(5) {
            display: none;
            width: 0;
            height: 0;
            opacity: 0;
            visibility: collapse;
        }
    }
</style>

<!-- To Copy Start -->
<div class="vh-100 p-3" style="background-color: lightgray;">

    <div class="row d-flex justify-content-center">
        <div class="col">

            <div class="card" style="border-radius: 15px;">
                <div class="card-body p-3">
                    <!-- Insert Content Start -->
                    <div class="text-center">
                        <img src="~/Content/Images/check1.png" alt="Check" style="height: 100px; width: 100px">
                        <h2 class="my-4">Task List</h2>
                    </div>

                    @using (Html.BeginForm("Show", "DailyTask", FormMethod.Post, new { @Id = "invoiceTaskForm" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="row m-2 align-items-center">
                            <div class="col-2 text-end">
                                <label style="font-size: 18px;">Filter</label>
                            </div>
                            <div class="col-6 input_req">
                                @Html.TextBoxFor(model => model.invoice_completed_date, "{0:yyyy-MM-dd}", new { @Class = "form-control", @Type = "date" })
                            </div>
                            <div class="col-2">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    }

                    <hr />

                    <div id="invoiceTaskContent">
                        @Html.Action("DailyTaskPartial")
                    </div>

                    <!-- Insert Content End-->
                </div>
            </div>

        </div>
    </div>
</div>
<!-- To Copy End -->



<script type="text/javascript">
    $(function () {

        let invoice_date_form = $("form[id='invoiceTaskForm']");
        const invoice_date_actionLink = invoice_date_form.attr("action");
        const invoice_date_methodType = invoice_date_form.attr("method");

        invoice_date_form.submit(e => {
            e.preventDefault();

            let input_valArr = [...document.getElementsByClassName("input_req")]
                .map((node, ind) => node.querySelector("input[type=date]").value)
                .map(node => (node == "") ? 0 : 1);
            let submit_flag = Math.min(...input_valArr);

            if (submit_flag) {
                $.ajax({
                    type: invoice_date_methodType,
                    url: invoice_date_actionLink,
                    data: invoice_date_form.serialize(),
                    success: resp => {
                        $("#invoiceTaskContent").html(resp);
                    }
                });
            }
        });
    });
</script>

dbShopeeAutomationV2/dbShopeeAutomationV2/Views/DailyTask/_DailyTaskPartial.cshtml
@using dbShopeeAutomationV2.Models;
@using System.Collections.Generic;
@model IEnumerable<TShopeeInvoice>

@{
    dbShopeeAutomationV2Entities db = new dbShopeeAutomationV2Entities();

    Dictionary<int, string> statusDict = new Dictionary<int, string>();
    db.TShopeeInvoiceStatus.ToList().ForEach(it => statusDict.Add(it.invoice_status_id, it.name));
}

<div class="text-center">
    <h4>Number of Orders: <span id="num_of_order_left">@ViewData["num_of_orders_left"]</span></h4>
</div>

<div class="my-2"></div>

<div class="d-flex align-items-center justify-content-center">
    <div>
        @using (Html.BeginForm("GenerateSummary", "DailyTask", FormMethod.Post, new { @Id = "generateSummaryForm" }))
        {
            @Html.AntiForgeryToken()

            <input id="generateSummaryBtn" type="submit" class="btn btn-success" value="Generate Summary Listing" disabled />
        }
    </div>
</div>

<div style="display: none;">
    @using (Html.BeginForm("PrintBill", "DailyTask", FormMethod.Post, new { @Id = "generateInvoiceBillForm" }))
    {
        @Html.AntiForgeryToken()
    }
</div>

<div class="my-2"></div>

<div class="border border-dark">
    <table class="table table-striped">
        <thead class="bg-dark text-white text-center">
            <tr>
                <th><input type="checkbox" id="selectAll"></th>
                <th>Invoice Code</th>
                <th>Created Date</th>
                <th>Complete?</th>
                <th>Completed Date</th>
                <th>Print</th>
            </tr>
        </thead>
        <tbody class="text-center">
            @for (int i = 0; i < Model.ToList().Count; i++)
            {
                var inv_rec = Model.ElementAt(i);
                string ind = $"{i + 1}";
                string tmp_com_dt = (inv_rec.invoice_completed_date == null) ? "" : inv_rec.invoice_completed_date.Value.ToString("yyyy-MM-dd");
                <tr>
                    <td><input type="checkbox" name="invoice_id" value="@inv_rec.invoice_id" form="generateSummaryForm"></td>
                    <td>@inv_rec.invoice_title</td>
                    <td>@inv_rec.invoice_created_date.Value.ToString("yyyy-MM-dd")</td>
                    <td>@statusDict[(int)inv_rec.invoice_status_id]</td>
                    <td>@tmp_com_dt</td>
                    <td><button class="btn btn-danger print_bill_btn" value="@inv_rec.invoice_id" type="button">Print</button></td>
                </tr>
                }
        </tbody>
    </table>
</div>

<div id="summary_pdf" style="display: none;"></div>
<div id="invoice_pdf" style="display: none;"></div>

<script type="text/javascript">
    $(function () {
        // Loop Through Complete Status
        $("tbody tr td:nth-child(4)").each((ind, elem) => {
            if (elem.innerHTML.toLowerCase() == "Complete".toLowerCase()) {
                // Enable Disable
                let checkbox_elem = $(`tbody tr:nth-child(${ind + 1}) input[type="checkbox"]`);
                checkbox_elem.remove();
            }
        });

        // Select/Deselect checkboxes
        let checkbox = $('table tbody input[type="checkbox"]');

        $("#selectAll").click(function () {
            if (this.checked) {
                let flag = false;
                checkbox.each(function () {
                    this.checked = true;
                    flag = true;
                });
                $("#generateSummaryBtn").prop("disabled", !flag);
            } else {
                $("#generateSummaryBtn").prop("disabled", true);
                checkbox.each(function () {
                    this.checked = false;
                });
            }
        });

        checkbox.on("change", e => {
            if (!this.checked) {
                $("#selectAll").prop("checked", false);
            }

            let flag = false;
            checkbox.each(function () {
                if (this.checked) {
                    $("#generateSummaryBtn").prop("disabled", false);
                    flag = true;
                }
            });
            $("#generateSummaryBtn").prop("disabled", !flag);

        });

        formatTD = x => (x < 10) ? `0${x}` : x + "";
        formatAMPM = x => (x < 12) ? "AM" : "PM";
        formatHR = x => (x >= 12) ? x % 12 : x;

        let generateSummaryForm = $("form[id='generateSummaryForm']");
        const generate_summary_actionLink = generateSummaryForm.attr("action");
        const generate_summary_methodType = generateSummaryForm.attr("method");

        generateSummaryForm.submit(e => {
            e.preventDefault();

            $.ajax({
                type: generate_summary_methodType,
                url: generate_summary_actionLink,
                data: generateSummaryForm.serialize(),
                success: resp => {
                    $("#generateSummaryBtn").prop("disabled", true);

                    $("#summary_pdf").html(resp);
                    let date = new Date(), fileName = `${date.getFullYear()}${formatTD(date.getMonth() + 1)}${formatTD(date.getDate())}_${formatTD(formatHR(date.getHours()))}${formatTD(date.getMinutes())}${formatTD(date.getSeconds())}${formatAMPM(date.getHours())}_summary_listing`;

                    createPDF("summary_pdf", fileName);

                    setTimeout(_ => { location.reload(); }, 5000);
                }
            });

            checkbox.each(function () {
                this.checked = false;
            });

            $("#selectAll").prop("checked", false);
        });

        let generateInvoiceBillForm = $("form[id='generateInvoiceBillForm']")
        const generate_invoice_bill_actionLink = generateInvoiceBillForm.attr("action");
        const generate_invoice_bill_methodType = generateInvoiceBillForm.attr("method");

        $(".print_bill_btn").on("click", e => {
            let invoice_id = e.currentTarget.value;

            $.ajax({
                type: generate_invoice_bill_methodType,
                url: generate_invoice_bill_actionLink,
                data: { "invoice_id": invoice_id },
                success: resp => {
                    $("#invoice_pdf").html(resp);
                    let invoice_code = $("#invoice_code").html();
                    genQrCode(invoice_code);

                    // Format Invoice Form
                    $("#vend_logo").css("display", "none");

                    let date = new Date(), fileName = `${date.getFullYear()}${formatTD(date.getMonth() + 1)}${formatTD(date.getDate())}_${formatTD(formatHR(date.getHours()))}${formatTD(date.getMinutes())}${formatTD(date.getSeconds())}${formatAMPM(date.getHours())}_package_listing`;
                    createPDF("invoice_pdf", fileName);

                    // After Generating Payment
                    $("#vend_logo").css("display", "block");
                    $("#qrcode img").remove();
                }
            })
        });


    });
</script>

dbShopeeAutomationV2/dbShopeeAutomationV2/Views/DailyTask/_PackageListingPartial.cshtml
@using dbShopeeAutomationV2.Models;
@model PackageListingSummary

<style>
    .img {
        width: 200px;
        height: 200px;
    }

    .align-container {
        position: relative;
    }
    
    .align-container .align-left {
        text-align: left;
    }
    
    .align-container .align-right {
        text-align: right;
    }

    tr th,
    tr td {
        text-align: center;
    }

    tr th:last-child,
    tr td:last-child {
        text-align: left;
    }

    .invoice_footer {
        width: 100%;
        text-align: center;
        color: #777;
        border-top: 1px solid #aaa;
        padding: 8px 0;
    }
</style>

<section>
    <div class="card">
        <div class="card-body">
            <div class="row align-container">
                <div class="col-6">
                    <div class="d-flex">
                        <img alt="Company Logo" src="~/Content/Images/ntl_logo.png" id="vend_logo" />
                        <div id="qrcode"></div>
                    </div>
                </div>
                <div class="col-6 align-right">
                    <div class="h3 fw-bold">@Model.stockWarehouse.name</div>
                    <div>@Model.stockWarehouse.address_line_1, @Model.stockWarehouse.address_line_2</div>
                    <div>@Model.stockWarehouse.city, @Model.stockWarehouse.zip_code</div>
                    <div>@Model.stockWarehouse.state, @Model.stockWarehouse.country</div>
                    <div>@Model.stockWarehouse.phone_number</div>
                    <div>@Model.stockWarehouse.email_address</div>
                </div>
            </div>
            <hr />
            <div class="row align-container">
                <div class="col-6 h4 fw-bold">Shipping To</div>
                <div class="col-6 h4 fw-bold align-right">Invoice</div>
            </div>
            <div class="row align-container">
                <div class="col-6">
                    <div>@Model.customer.first_name @Model.customer.last_name</div>
                    <div>@Model.destAddress.address_line_1, @Model.destAddress.address_line_2</div>
                    <div>@Model.destAddress.city, @Model.destAddress.zip_code</div>
                    <div>@Model.destAddress.state, @Model.destAddress.country</div>
                </div>
                <div class="col-6 align-right">
                    <div id="invoice_code">@Model.invoice.invoice_title</div>
                    <div>@Model.invoice.invoice_created_date</div>
                    <div></div>
                    <div></div>
                </div>
            </div>

            <hr />

            <div class="h3 fw-bold">Order Summary</div>

            <table class="table table-borderless">
                <thead class="border-bottom bg-dark text-white">
                    <tr>
                        <th>No.</th>
                        <th>Item</th>
                        <th>Brand</th>
                        <th>Category</th>
                        <th>Model</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int ind = 0; ind < Model.productSummaryList.Count; ind++)
                    {
                        string no = $"{ind + 1}.";
                        var product = Model.productSummaryList.ElementAt(ind);
                        <tr>
                            <td>@no</td>
                            <td>@product.name</td>
                            <td>@product.product_brand</td>
                            <td>@product.product_category</td>
                            <td>@product.product_model</td>
                            <td>@product.product_type</td>
                            <td>RM @product.product_price</td>
                            <td>@product.quantity</td>
                            <td>RM @product.sub_total</td>
                        </tr>
                    }
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Subtotal</strong></td>
                        <td>@Model.sub_total</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Shipping</strong></td>
                        <td>@Model.invoice.shipping_fee</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Total</strong></td>
                        <td>@Model.total_price</td>
                    </tr>
                </tbody>
            </table>
            <div class="invoice_footer">
                Invoice was created on a computer and is valid without the signature and seal.
            </div>
        </div>
    </div>
</section>

dbShopeeAutomationV2/dbShopeeAutomationV2/Views/DailyTask/_SummaryListingPartial.cshtml
@using dbShopeeAutomationV2.Models;
@model IList<ProductSummary>

<section>
    <div class="card">
        <div class="card-body p-3">
            <div class="border border-dark">
                <table class="table table-borderless text-center">
                    <thead>
                        <tr class="bg-dark">
                            <th colspan="6" class="text-white h2">Product Summary Listing</th>
                        </tr>
                        <tr>
                            <th>No.</th>
                            <th>Name</th>
                            <th>Brand</th>
                            <th>Category</th>
                            <th>Model</th>
                            <th>Type</th>
                            <th>Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int ind = 0; ind < Model.ToList().Count; ind++)
                        {
                            var product = Model.ElementAt(ind);
                            string no = $"{ind + 1}.";
                            <tr>
                                <td>@no</td>
                                <td>@product.name</td>
                                <td>@product.product_brand</td>
                                <td>@product.product_category</td>
                                <td>@product.product_model</td>
                                <td>@product.product_type</td>
                                <td>@product.quantity</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>